export const angularjs = {name: "Angular Js", color: "#DF330A"}
export const reactjs = {name: "React Js", color: "#3470A3"}
export const reactNative = {name: "React Native", color: "#34A3A3"}
export const android = {name: "Android", color: "#37B920"}
export const kotlin = {name: "Kotlin", color: "#148400"}
export const java = {name: "Java", color: "#E35979"}
export const ios = {name: "iOS", color: "#297FE3"}
export const swift = {name: "Swift", color: "#3F5AA2"}
export const python = {name: "Python", color: "#DFA60A"}
export const flask = {name: "Flask", color: "#9B3D7A"}
export const php = {name: "PHP", color: "#DF770A"}
export const lumen = {name: "Lumen", color: "#7E3D9B"}
export const net = {name: ".NET", color: "#724949"}
